
language: java

jdk:
  - oraclejdk8

install:
  mvn --settings .settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V

# Install Erlang for integration tests
before_script:
  - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
  - sudo dpkg -i erlang-solutions_1.0_all.deb
  - sudo apt-get update -qq
  - sudo apt-get install elixir git -y
  - git clone https://github.com/appulse-projects/echo-service-elixir.git
  - (cd echo-service-elixir/; mix escript.build)
  - epmd -daemon
  - echo-service-elixir/echo --cookie=secret --name=echo@localhost &

script:
  mvn --settings .settings.xml clean verify -DskipTests=false -Dmaven.javadoc.skip=true -Dgpg.skip -B -U

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version | grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - sed -i -- "s/\${env.SONATYPE_PASSWORD}/$SONATYPE_PASSWORD/g" .settings.xml
  - mvn --settings .settings.xml clean deploy -DskipTests=true -Dmaven.javadoc.skip=false -B -U

deploy:
  provider: releases
  api_key:
    secure: YL2RHLS+TRdlGdkOveqdKzfexAoWdl4kJscmQiR2upAs355F6oOpaNvqae3jMtjDwb4ES7iDJZ/36bBAaF4oAe3ArEvHi4gIRtzLX1EkS5SeA1s3wiAgctp5JFkyo4FyRUgpXWiIGO0XL+qxGSc36t9rLOOJEAtwgPtpEEGB2rIwoYTwMCENcfV+NebXa9Lo2RTS84BwX6BzpyJDO5ZXg4skHzXMrcNmQV/+raX7J1jaTY++AIk0MRKwIpkXRJ4ozHt+Gxl31NBWN53A8Tu0mC2IkZ/fmNbZEbd8pR6UVhy3z+TBljgLfSLfSOjN+1h+4WSAMvEYzwmaFUuH+cfhhJesvjiw11o35+5wq189PK1h+Dj/+o8cemhNOtL/88CDsj36AEQiXTukIPKLPScrln5Ux/Z9so0oA9RYsLPX/tZU1WHak4S4lIcUlC2R3fDJEdNL6cf/bZIQXc9ld30qtlembOcx4aXnpLm64TR7UotppYTx4crs1GSTftqArfs/xSG4lmOuf2qW+Eyb1pZmycNzWo+K/RKCbcY9ep5dYnPyFTeY11EKLJK0FLQd2V0Q5NHpM6KjILA7bS8OpHVGsc4N9TawUCE2aokThbXJsPQE1K8Ya/Kaj9FdnlkQQrm5JkxsEJi+LXebWqLNACCOMhH4nYxDuMyMBUy1/OA+IZo=
  file:
    - "encon-common/target/encon-common-$project_version.jar"
    - "encon-common/target/encon-common-$project_version-javadoc.jar"
    - "encon-common/target/encon-common-$project_version-sources.jar"
    - "encon-terms/target/encon-terms-$project_version.jar"
    - "encon-terms/target/encon-terms-$project_version-javadoc.jar"
    - "encon-terms/target/encon-terms-$project_version-sources.jar"
    - "encon-config/target/encon-config-$project_version.jar"
    - "encon-config/target/encon-config-$project_version-javadoc.jar"
    - "encon-config/target/encon-config-$project_version-sources.jar"
    - "encon-databind/target/encon-databind-$project_version.jar"
    - "encon-databind/target/encon-databind-$project_version-javadoc.jar"
    - "encon-databind/target/encon-databind-$project_version-sources.jar"
    - "encon/target/encon-$project_version.jar"
    - "encon/target/encon-$project_version-javadoc.jar"
    - "encon/target/encon-$project_version-sources.jar"
    - "encon-handler/target/encon-handler-$project_version.jar"
    - "encon-handler/target/encon-handler-$project_version-javadoc.jar"
    - "encon-handler/target/encon-handler-$project_version-sources.jar"
    - "encon-spring/target/encon-spring-$project_version.jar"
    - "encon-spring/target/encon-spring-$project_version-javadoc.jar"
    - "encon-spring/target/encon-spring-$project_version-sources.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: appulse-projects/encon-java
  name: $project_version
