
spring.encon:
  nodes:
    node-1:
      type: R3_HIDDEN
      shortName: true
      cookie: non-secret
      protocol: TCP
      lowVersion: R5C
      highVersion: R6
      distributionFlags:
        - EXTENDED_REFERENCES
        - EXTENDED_PIDS_PORTS
        - BIT_BINARIES
        - NEW_FLOATS
        - FUN_TAGS
        - NEW_FUN_TAGS
        - UTF8_ATOMS
        - MAP_TAG
        - BIG_CREATION
      server:
        port: 8971
        bossThreads: 1
        workerThreads: 2

    node-2:
      type: R3_ERLANG
      shortName: false
      cookie: popa
      protocol: TCP
      lowVersion: R4
      highVersion: R6
      distributionFlags:
        - MAP_TAG
        - BIG_CREATION
      server:
        bossThreads: 2
        workerThreads: 4
